<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Czujnik_NC" Id="{51ba7fa6-f7c0-4afd-bbfe-dc8f49c5646a}" SpecialFunc="None">
    <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.06.2022
//	Obsługa czujnika NC
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
FUNCTION_BLOCK FB_Czujnik_NC IMPLEMENTS ITF_Czujnik
VAR
	bWejscie						AT %I*	: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="CzyZadzialany" Id="{fc66beb3-2c43-4161-beb6-70ba35ef7689}">
      <Declaration><![CDATA[//==================================================================================================
//								RJM Maszyny sp. z o.o.
//									04.06.2022
//	Obsługa czujnika  
// 	v1.0	|| TC v 3.1.4024.22		|| - pierwsza wersja
//==================================================================================================
PROPERTY CzyZadzialany : BOOL
]]></Declaration>
      <Get Name="Get" Id="{a9c273e3-8246-498a-9fbf-8e32a7aeaa7f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[CzyZadzialany								:= NOT bWejscie;
]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="FB_Czujnik_NC">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Czujnik_NC.CzyZadzialany.Get">
      <LineId Id="2" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>